name: Continuous Integration
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm run build

      - uses: actions/upload-artifact@v3
        with:
          name: smart-home
          path: build

  deploy-dev:
    runs-on: ubuntu-latest
    environment: development
    needs: build
    steps:
      - run: echo deploying dev envrionment

  post-deployment-tests-dev:
    runs-on: ubuntu-latest
    environment: development
    needs: [build, deploy-dev]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: |
          pip install robotframework-browser==14.4.1
          pip install rpaframework==22.0.0
          rfbrowser init
          python -m robot --outputdir output --logtitle "Task log" ./acceptance-tests/tasks.robot
      - uses: actions/upload-artifact@v3
        with:
          name: acceptance-test-dev
          path: output

  deploy-stg-wave-1:
    runs-on: ubuntu-latest
    environment: staging-wave-1
    needs: [build, deploy-dev, post-deployment-tests-dev]
    steps:
      - run: echo deploying stg envrionment

  # post-deployment-tests:
  #   runs-on: ubuntu-latest
  #   environment: staging-wave-1
  #   needs: [build, deploy-dev, deploy-stg-wave-1]
  #   steps:
  #     - run: running post deployment tests on staging wave-1

  # deploy-stg-wave-2:
  #   runs-on: ubuntu-latest
  #   environment: staging-wave-2
  #   needs: build
  #   steps:
  #     - run: echo deploying stg envrionment

  # deploy-prod:
  #   runs-on: ubuntu-latest
  #   environment: production
  #   needs: [build, deploy-dev]
  #   steps:
  #     - run: echo deploying prod environment

      
